# This file was generated by GoReleaser. DO NOT EDIT.
cask "zensu" do
  version "0.5.6"

  on_macos do
    on_intel do
      sha256 "752d8f38fb2304a77255e955f1b086b29cfcaadaab2b28e6b01990afa28ef42f"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "494f5622afd4469911104691c2a9874d27f96d44d82083f155312869ab932c82"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "df238e633178baa744f974ed6e5e326fa9e9e76f4ef2cf1c2ed26e84d1cdbbac"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b734e56802d0f341046747d12417600a38563643efc3540c60ababa6390089ad"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zensu"
  desc "GitHub-CLI-style terminal client for the Zensu Product Lifecycle Manager"
  homepage "https://zensu.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zensu"

  # No zap stanza required

end
