# This file was generated by GoReleaser. DO NOT EDIT.
cask "zensu" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "ac8b2a841c3949435218798a46b04e20895054ca51fa4bf1914e1e2c04bb387e"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fece43c052adadd1f4ad25ae26635d27809b61028f4f3d53510c0a6d2c1ac103"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eec2bf838042ed220bf82d5bf349409186bcb18775799fd4240c76633d8cccf7"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6514357da87a6104f80fda6a79279a1b4e13b6b2d8b9c717e4ee7067b5e8331"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zensu"
  desc "GitHub-CLI-style terminal client for the Zensu Product Lifecycle Manager"
  homepage "https://zensu.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zensu"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zensu"] if OS.mac?
  end

  # No zap stanza required

end
