# This file was generated by GoReleaser. DO NOT EDIT.
cask "zensu" do
  version "0.5.7"

  on_macos do
    on_intel do
      sha256 "99fe81797e78b5a7cf74cfca5fa1b1e1ab64fdba41c4743a1ccce7dff120b2ac"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "992db090a9aaa68530f0c06bac3e1fcaa2c2285973a38905df4bc8feb604822d"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0cb4eef1a11b71a31168ac504b373a29a72b8ff41d267ef0dbb506f80f23a97"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "05dc2ce12088de3b25566455b136e70e94bdbc2c047131c95d400ce5a3fe48f6"
      url "https://github.com/MKITConsulting/zensu-cli/releases/download/v#{version}/zensu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zensu"
  desc "GitHub-CLI-style terminal client for the Zensu Product Lifecycle Manager"
  homepage "https://zensu.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zensu"

  # No zap stanza required

end
